// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore.DataContext;

#nullable disable

namespace Repositories.EFCore.Migrations
{
    [DbContext(typeof(MusicfyContext))]
    [Migration("20221106023133_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.POCOEntities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Bad Bunny",
                            ImageURL = "https://i1.sndcdn.com/artworks-lJMUnZEnRcJBpzvx-DftmXA-t500x500.jpg",
                            Name = "El Ultimo Tour del Mundo",
                            Status = true,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Morat",
                            ImageURL = "https://master.com.ar/wp-content/uploads/0157657001625861386.jpg",
                            Name = "¿A Donde Vamos?",
                            Status = true,
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
